return {
    -- "sphamba/smear-cursor.nvim",
    -- opts = {
    --     -- Smear cursor when switching buffers or windows.
    --     smear_between_buffers = true,
    --
    --     -- Smear cursor when moving within line or to neighbor lines.
    --     smear_between_neighbor_lines = true,
    --
    --     -- Draw the smear in buffer space instead of screen space when scrolling
    --     scroll_buffer_space = true,
    --
    --     -- Set to `true` if your font supports legacy computing symbols (block unicode symbols).
    --     -- Smears will blend better on all backgrounds.
    --     legacy_computing_symbols_support = true,
    --
    --     stiffness = 0.8,                 -- 0.6      [0, 1]
    --     trailing_stiffness = 0.5,        -- 0.3      [0, 1]
    --     distance_stop_animating = 0.01,  -- 0.1      > 0
    --     hide_target_hack = true,         -- true     boolean
    --
    --     delay_animation_start = 3,       -- 5        milliseconds
    --     time_interval = 10,              -- 17       milliseconds
    --     slowdown_exponent = -0.2,        -- 0        < 0: less slowdown, > 0: more slowdown. Keep small, e.g. [-0.2, 0.2]
    --     max_shade_no_matrix = 0.75,      -- 0: more overhangs, 1: more matrices
    --     matrix_pixel_threshold = 0.7,    -- 0: all pixels, 1: no pixel
    --     matrix_pixel_min_factor = 0.5,   -- 0: all pixels, 1: no pixel
    --     volume_reduction_exponent = 0.3, -- 0: no reduction, 1: full reduction
    --     minimum_volume_factor = 0.7,     -- 0: no limit, 1: no reduction
    --     max_length = 25,                 -- Maximum smear length
    --
    -- },
    -- enable = false,
}
